package diligent

type License struct {
	Identifier string
	Name       string
	URL        string
}

var lookup = map[string]License{
	"Glide":                                {Identifier: "Glide", Name: "3dfx Glide License", URL: "http://www.users.on.net/~triforce/glidexp/COPYING.txt"},
	"Abstyles":                             {Identifier: "Abstyles", Name: "Abstyles License", URL: "https://fedoraproject.org/wiki/Licensing/Abstyles"},
	"AFL-1.1":                              {Identifier: "AFL-1.1", Name: "Academic Free License v1.1", URL: "http://opensource.linux-mirror.org/licenses/afl-1.1.txt"},
	"AFL-1.2":                              {Identifier: "AFL-1.2", Name: "Academic Free License v1.2", URL: "http://opensource.linux-mirror.org/licenses/afl-1.2.txt"},
	"AFL-2.0":                              {Identifier: "AFL-2.0", Name: "Academic Free License v2.0", URL: "http://opensource.linux-mirror.org/licenses/afl-2.0.txt"},
	"AFL-2.1":                              {Identifier: "AFL-2.1", Name: "Academic Free License v2.1", URL: "http://opensource.linux-mirror.org/licenses/afl-2.1.txt"},
	"AFL-3.0":                              {Identifier: "AFL-3.0", Name: "Academic Free License v3.0", URL: "http://www.rosenlaw.com/AFL3.0.htm"},
	"AMPAS":                                {Identifier: "AMPAS", Name: "Academy of Motion Picture Arts and Sciences BSD", URL: "https://fedoraproject.org/wiki/Licensing/BSD#AMPASBSD"},
	"APL-1.0":                              {Identifier: "APL-1.0", Name: "Adaptive Public License 1.0", URL: "http://www.opensource.org/licenses/APL-1.0"},
	"Adobe-Glyph":                          {Identifier: "Adobe-Glyph", Name: "Adobe Glyph List License", URL: "https://fedoraproject.org/wiki/Licensing/MIT#AdobeGlyph"},
	"APAFML":                               {Identifier: "APAFML", Name: "Adobe Postscript AFM License", URL: "https://fedoraproject.org/wiki/Licensing/AdobePostscriptAFM"},
	"Adobe-2006":                           {Identifier: "Adobe-2006", Name: "Adobe Systems Incorporated Source Code License Agreement", URL: "https://fedoraproject.org/wiki/Licensing/AdobeLicense"},
	"AGPL-1.0":                             {Identifier: "AGPL-1.0", Name: "Affero General Public License v1.0", URL: "http://www.affero.org/oagpl.html"},
	"Afmparse":                             {Identifier: "Afmparse", Name: "Afmparse License", URL: "https://fedoraproject.org/wiki/Licensing/Afmparse"},
	"Aladdin":                              {Identifier: "Aladdin", Name: "Aladdin Free Public License", URL: "http://pages.cs.wisc.edu/~ghost/doc/AFPL/6.01/Public.htm"},
	"ADSL":                                 {Identifier: "ADSL", Name: "Amazon Digital Services License", URL: "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"},
	"AMDPLPA":                              {Identifier: "AMDPLPA", Name: "AMD's plpa_map.c License", URL: "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"},
	"ANTLR-PD":                             {Identifier: "ANTLR-PD", Name: "ANTLR Software Rights Notice", URL: "http://www.antlr2.org/license.html"},
	"Apache-1.0":                           {Identifier: "Apache-1.0", Name: "Apache License 1.0", URL: "http://www.apache.org/licenses/LICENSE-1.0"},
	"Apache-1.1":                           {Identifier: "Apache-1.1", Name: "Apache License 1.1", URL: "http://apache.org/licenses/LICENSE-1.1"},
	"Apache-2.0":                           {Identifier: "Apache-2.0", Name: "Apache License 2.0", URL: "http://www.apache.org/licenses/LICENSE-2.0"},
	"AML":                                  {Identifier: "AML", Name: "Apple MIT License", URL: "https://fedoraproject.org/wiki/Licensing/Apple_MIT_License"},
	"APSL-1.0":                             {Identifier: "APSL-1.0", Name: "Apple Public Source License 1.0", URL: "https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0"},
	"APSL-1.1":                             {Identifier: "APSL-1.1", Name: "Apple Public Source License 1.1", URL: "http://www.opensource.apple.com/source/IOSerialFamily/IOSerialFamily-7/APPLE_LICENSE"},
	"APSL-1.2":                             {Identifier: "APSL-1.2", Name: "Apple Public Source License 1.2", URL: "http://www.samurajdata.se/opensource/mirror/licenses/apsl.php"},
	"APSL-2.0":                             {Identifier: "APSL-2.0", Name: "Apple Public Source License 2.0", URL: "http://www.opensource.apple.com/license/apsl/"},
	"Artistic-1.0":                         {Identifier: "Artistic-1.0", Name: "Artistic License 1.0", URL: "http://opensource.org/licenses/Artistic-1.0"},
	"Artistic-1.0-Perl":                    {Identifier: "Artistic-1.0-Perl", Name: "Artistic License 1.0 (Perl)", URL: "http://dev.perl.org/licenses/artistic.html"},
	"Artistic-1.0-cl8":                     {Identifier: "Artistic-1.0-cl8", Name: "Artistic License 1.0 w/clause 8", URL: "http://opensource.org/licenses/Artistic-1.0"},
	"Artistic-2.0":                         {Identifier: "Artistic-2.0", Name: "Artistic License 2.0", URL: "http://www.perlfoundation.org/artistic_license_2_0"},
	"AAL":                                  {Identifier: "AAL", Name: "Attribution Assurance License", URL: "http://www.opensource.org/licenses/attribution"},
	"Bahyph":                               {Identifier: "Bahyph", Name: "Bahyph License", URL: "https://fedoraproject.org/wiki/Licensing/Bahyph"},
	"Barr":                                 {Identifier: "Barr", Name: "Barr License", URL: "https://fedoraproject.org/wiki/Licensing/Barr"},
	"Beerware":                             {Identifier: "Beerware", Name: "Beerware License", URL: "https://fedoraproject.org/wiki/Licensing/Beerware"},
	"BitTorrent-1.0":                       {Identifier: "BitTorrent-1.0", Name: "BitTorrent Open Source License v1.0", URL: "http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s"},
	"BitTorrent-1.1":                       {Identifier: "BitTorrent-1.1", Name: "BitTorrent Open Source License v1.1", URL: "http://directory.fsf.org/wiki/License:BitTorrentOSL1.1"},
	"BSL-1.0":                              {Identifier: "BSL-1.0", Name: "Boost Software License 1.0", URL: "http://www.boost.org/LICENSE_1_0.txt"},
	"Borceux":                              {Identifier: "Borceux", Name: "Borceux license", URL: "https://fedoraproject.org/wiki/Licensing/Borceux"},
	"BSD-2-Clause":                         {Identifier: "BSD-2-Clause", Name: "BSD 2-clause \"Simplified\" License", URL: "http://www.opensource.org/licenses/BSD-2-Clause"},
	"BSD-2-Clause-FreeBSD":                 {Identifier: "BSD-2-Clause-FreeBSD", Name: "BSD 2-clause FreeBSD License", URL: "http://www.freebsd.org/copyright/freebsd-license.html"},
	"BSD-2-Clause-NetBSD":                  {Identifier: "BSD-2-Clause-NetBSD", Name: "BSD 2-clause NetBSD License", URL: "http://www.netbsd.org/about/redistribution.html#default"},
	"BSD-3-Clause":                         {Identifier: "BSD-3-Clause", Name: "BSD 3-clause \"New\" or \"Revised\" License", URL: "http://www.opensource.org/licenses/BSD-3-Clause"},
	"BSD-3-Clause-Clear":                   {Identifier: "BSD-3-Clause-Clear", Name: "BSD 3-clause Clear License", URL: "http://labs.metacarta.com/license-explanation.html#license"},
	"BSD-3-Clause-No-Nuclear-License":      {Identifier: "BSD-3-Clause-No-Nuclear-License", Name: "BSD 3-Clause No Nuclear License", URL: "http://download.oracle.com/otn-pub/java/licenses/bsd.txt?AuthParam=1467140197_43d516ce1776bd08a58235a7785be1cc"},
	"BSD-3-Clause-No-Nuclear-License-2014": {Identifier: "BSD-3-Clause-No-Nuclear-License-2014", Name: "BSD 3-Clause No Nuclear License 2014", URL: "https://java.net/projects/javaeetutorial/pages/BerkeleyLicense"},
	"BSD-3-Clause-No-Nuclear-Warranty":     {Identifier: "BSD-3-Clause-No-Nuclear-Warranty", Name: "BSD 3-Clause No Nuclear Warranty", URL: "https://jogamp.org/git/?p=gluegen.git;a=blob_plain;f=LICENSE.txt"},
	"BSD-4-Clause":                         {Identifier: "BSD-4-Clause", Name: "BSD 4-clause \"Original\" or \"Old\" License", URL: "http://directory.fsf.org/wiki/License:BSD_4Clause"},
	"BSD-Protection":                       {Identifier: "BSD-Protection", Name: "BSD Protection License", URL: "https://fedoraproject.org/wiki/Licensing/BSD_Protection_License"},
	"BSD-Source-Code":                      {Identifier: "BSD-Source-Code", Name: "BSD Source Code Attribution", URL: "https://github.com/robbiehanson/CocoaHTTPServer/blob/master/LICENSE.txt"},
	"BSD-3-Clause-Attribution":             {Identifier: "BSD-3-Clause-Attribution", Name: "BSD with attribution", URL: "https://fedoraproject.org/wiki/Licensing/BSD_with_Attribution"},
	"0BSD":                             {Identifier: "0BSD", Name: "BSD Zero Clause License", URL: "http://landley.net/toybox/license.html"},
	"BSD-4-Clause-UC":                  {Identifier: "BSD-4-Clause-UC", Name: "BSD-4-Clause (University of California-Specific)", URL: "http://www.freebsd.org/copyright/license.html"},
	"bzip2-1.0.5":                      {Identifier: "bzip2-1.0.5", Name: "bzip2 and libbzip2 License v1.0.5", URL: "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html"},
	"bzip2-1.0.6":                      {Identifier: "bzip2-1.0.6", Name: "bzip2 and libbzip2 License v1.0.6", URL: "https://github.com/asimonov-im/bzip2/blob/master/LICENSE"},
	"Caldera":                          {Identifier: "Caldera", Name: "Caldera License", URL: "http://www.lemis.com/grog/UNIX/ancient-source-all.pdf"},
	"CECILL-1.0":                       {Identifier: "CECILL-1.0", Name: "CeCILL Free Software License Agreement v1.0", URL: "http://www.cecill.info/licences/Licence_CeCILL_V1-fr.html"},
	"CECILL-1.1":                       {Identifier: "CECILL-1.1", Name: "CeCILL Free Software License Agreement v1.1", URL: "http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html"},
	"CECILL-2.0":                       {Identifier: "CECILL-2.0", Name: "CeCILL Free Software License Agreement v2.0", URL: "http://www.cecill.info/licences/Licence_CeCILL_V2-fr.html"},
	"CECILL-2.1":                       {Identifier: "CECILL-2.1", Name: "CeCILL Free Software License Agreement v2.1", URL: "http://www.cecill.info/licences/Licence_CeCILL_V2.1-fr.html"},
	"CECILL-B":                         {Identifier: "CECILL-B", Name: "CeCILL-B Free Software License Agreement", URL: "http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.html"},
	"CECILL-C":                         {Identifier: "CECILL-C", Name: "CeCILL-C Free Software License Agreement", URL: "http://www.cecill.info/licences/Licence_CeCILL-C_V1-fr.html"},
	"ClArtistic":                       {Identifier: "ClArtistic", Name: "Clarified Artistic License", URL: "http://www.ncftp.com/ncftp/doc/LICENSE.txt"},
	"MIT-CMU":                          {Identifier: "MIT-CMU", Name: "CMU License", URL: "https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#CMU_Style"},
	"CNRI-Jython":                      {Identifier: "CNRI-Jython", Name: "CNRI Jython License", URL: "http://www.jython.org/license.html"},
	"CNRI-Python":                      {Identifier: "CNRI-Python", Name: "CNRI Python License", URL: "http://www.opensource.org/licenses/CNRI-Python"},
	"CNRI-Python-GPL-Compatible":       {Identifier: "CNRI-Python-GPL-Compatible", Name: "CNRI Python Open Source GPL Compatible License Agreement", URL: "http://www.python.org/download/releases/1.6.1/download_win/"},
	"CPOL-1.02":                        {Identifier: "CPOL-1.02", Name: "Code Project Open License 1.02", URL: "http://www.codeproject.com/info/cpol10.aspx"},
	"CDDL-1.0":                         {Identifier: "CDDL-1.0", Name: "Common Development and Distribution License 1.0", URL: "http://www.opensource.org/licenses/cddl1"},
	"CDDL-1.1":                         {Identifier: "CDDL-1.1", Name: "Common Development and Distribution License 1.1", URL: "http://glassfish.java.net/public/CDDL+GPL_1_1.html"},
	"CPAL-1.0":                         {Identifier: "CPAL-1.0", Name: "Common Public Attribution License 1.0", URL: "http://www.opensource.org/licenses/CPAL-1.0"},
	"CPL-1.0":                          {Identifier: "CPL-1.0", Name: "Common Public License 1.0", URL: "http://opensource.org/licenses/CPL-1.0"},
	"CATOSL-1.1":                       {Identifier: "CATOSL-1.1", Name: "Computer Associates Trusted Open Source License 1.1", URL: "http://opensource.org/licenses/CATOSL-1.1"},
	"Condor-1.1":                       {Identifier: "Condor-1.1", Name: "Condor Public License v1.1", URL: "http://research.cs.wisc.edu/condor/license.html#condor"},
	"CC-BY-1.0":                        {Identifier: "CC-BY-1.0", Name: "Creative Commons Attribution 1.0", URL: "http://creativecommons.org/licenses/by/1.0/legalcode"},
	"CC-BY-2.0":                        {Identifier: "CC-BY-2.0", Name: "Creative Commons Attribution 2.0", URL: "http://creativecommons.org/licenses/by/2.0/legalcode"},
	"CC-BY-2.5":                        {Identifier: "CC-BY-2.5", Name: "Creative Commons Attribution 2.5", URL: "http://creativecommons.org/licenses/by/2.5/legalcode"},
	"CC-BY-3.0":                        {Identifier: "CC-BY-3.0", Name: "Creative Commons Attribution 3.0", URL: "http://creativecommons.org/licenses/by/3.0/legalcode"},
	"CC-BY-4.0":                        {Identifier: "CC-BY-4.0", Name: "Creative Commons Attribution 4.0", URL: "http://creativecommons.org/licenses/by/4.0/legalcode"},
	"CC-BY-ND-1.0":                     {Identifier: "CC-BY-ND-1.0", Name: "Creative Commons Attribution No Derivatives 1.0", URL: "http://creativecommons.org/licenses/by-nd/1.0/legalcode"},
	"CC-BY-ND-2.0":                     {Identifier: "CC-BY-ND-2.0", Name: "Creative Commons Attribution No Derivatives 2.0", URL: "http://creativecommons.org/licenses/by-nd/2.0/legalcode"},
	"CC-BY-ND-2.5":                     {Identifier: "CC-BY-ND-2.5", Name: "Creative Commons Attribution No Derivatives 2.5", URL: "http://creativecommons.org/licenses/by-nd/2.5/legalcode"},
	"CC-BY-ND-3.0":                     {Identifier: "CC-BY-ND-3.0", Name: "Creative Commons Attribution No Derivatives 3.0", URL: "http://creativecommons.org/licenses/by-nd/3.0/legalcode"},
	"CC-BY-ND-4.0":                     {Identifier: "CC-BY-ND-4.0", Name: "Creative Commons Attribution No Derivatives 4.0", URL: "http://creativecommons.org/licenses/by-nd/4.0/legalcode"},
	"CC-BY-NC-1.0":                     {Identifier: "CC-BY-NC-1.0", Name: "Creative Commons Attribution Non Commercial 1.0", URL: "http://creativecommons.org/licenses/by-nc/1.0/legalcode"},
	"CC-BY-NC-2.0":                     {Identifier: "CC-BY-NC-2.0", Name: "Creative Commons Attribution Non Commercial 2.0", URL: "http://creativecommons.org/licenses/by-nc/2.0/legalcode"},
	"CC-BY-NC-2.5":                     {Identifier: "CC-BY-NC-2.5", Name: "Creative Commons Attribution Non Commercial 2.5", URL: "http://creativecommons.org/licenses/by-nc/2.5/legalcode"},
	"CC-BY-NC-3.0":                     {Identifier: "CC-BY-NC-3.0", Name: "Creative Commons Attribution Non Commercial 3.0", URL: "http://creativecommons.org/licenses/by-nc/3.0/legalcode"},
	"CC-BY-NC-4.0":                     {Identifier: "CC-BY-NC-4.0", Name: "Creative Commons Attribution Non Commercial 4.0", URL: "http://creativecommons.org/licenses/by-nc/4.0/legalcode"},
	"CC-BY-NC-ND-1.0":                  {Identifier: "CC-BY-NC-ND-1.0", Name: "Creative Commons Attribution Non Commercial No Derivatives 1.0", URL: "http://creativecommons.org/licenses/by-nd-nc/1.0/legalcode"},
	"CC-BY-NC-ND-2.0":                  {Identifier: "CC-BY-NC-ND-2.0", Name: "Creative Commons Attribution Non Commercial No Derivatives 2.0", URL: "http://creativecommons.org/licenses/by-nc-nd/2.0/legalcode"},
	"CC-BY-NC-ND-2.5":                  {Identifier: "CC-BY-NC-ND-2.5", Name: "Creative Commons Attribution Non Commercial No Derivatives 2.5", URL: "http://creativecommons.org/licenses/by-nc-nd/2.5/legalcode"},
	"CC-BY-NC-ND-3.0":                  {Identifier: "CC-BY-NC-ND-3.0", Name: "Creative Commons Attribution Non Commercial No Derivatives 3.0", URL: "http://creativecommons.org/licenses/by-nc-nd/3.0/legalcode"},
	"CC-BY-NC-ND-4.0":                  {Identifier: "CC-BY-NC-ND-4.0", Name: "Creative Commons Attribution Non Commercial No Derivatives 4.0", URL: "http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode"},
	"CC-BY-NC-SA-1.0":                  {Identifier: "CC-BY-NC-SA-1.0", Name: "Creative Commons Attribution Non Commercial Share Alike 1.0", URL: "http://creativecommons.org/licenses/by-nc-sa/1.0/legalcode"},
	"CC-BY-NC-SA-2.0":                  {Identifier: "CC-BY-NC-SA-2.0", Name: "Creative Commons Attribution Non Commercial Share Alike 2.0", URL: "http://creativecommons.org/licenses/by-nc-sa/2.0/legalcode"},
	"CC-BY-NC-SA-2.5":                  {Identifier: "CC-BY-NC-SA-2.5", Name: "Creative Commons Attribution Non Commercial Share Alike 2.5", URL: "http://creativecommons.org/licenses/by-nc-sa/2.5/legalcode"},
	"CC-BY-NC-SA-3.0":                  {Identifier: "CC-BY-NC-SA-3.0", Name: "Creative Commons Attribution Non Commercial Share Alike 3.0", URL: "http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode"},
	"CC-BY-NC-SA-4.0":                  {Identifier: "CC-BY-NC-SA-4.0", Name: "Creative Commons Attribution Non Commercial Share Alike 4.0", URL: "http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"},
	"CC-BY-SA-1.0":                     {Identifier: "CC-BY-SA-1.0", Name: "Creative Commons Attribution Share Alike 1.0", URL: "http://creativecommons.org/licenses/by-sa/1.0/legalcode"},
	"CC-BY-SA-2.0":                     {Identifier: "CC-BY-SA-2.0", Name: "Creative Commons Attribution Share Alike 2.0", URL: "http://creativecommons.org/licenses/by-sa/2.0/legalcode"},
	"CC-BY-SA-2.5":                     {Identifier: "CC-BY-SA-2.5", Name: "Creative Commons Attribution Share Alike 2.5", URL: "http://creativecommons.org/licenses/by-sa/2.5/legalcode"},
	"CC-BY-SA-3.0":                     {Identifier: "CC-BY-SA-3.0", Name: "Creative Commons Attribution Share Alike 3.0", URL: "http://creativecommons.org/licenses/by-sa/3.0/legalcode"},
	"CC-BY-SA-4.0":                     {Identifier: "CC-BY-SA-4.0", Name: "Creative Commons Attribution Share Alike 4.0", URL: "http://creativecommons.org/licenses/by-sa/4.0/legalcode"},
	"CC0-1.0":                          {Identifier: "CC0-1.0", Name: "Creative Commons Zero v1.0 Universal", URL: "http://creativecommons.org/publicdomain/zero/1.0/legalcode"},
	"Crossword":                        {Identifier: "Crossword", Name: "Crossword License", URL: "https://fedoraproject.org/wiki/Licensing/Crossword"},
	"CrystalStacker":                   {Identifier: "CrystalStacker", Name: "CrystalStacker License", URL: "https://fedoraproject.org/wiki/Licensing:CrystalStacker?rd=Licensing/CrystalStacker"},
	"CUA-OPL-1.0":                      {Identifier: "CUA-OPL-1.0", Name: "CUA Office Public License v1.0", URL: "http://opensource.org/licenses/CUA-OPL-1.0"},
	"Cube":                             {Identifier: "Cube", Name: "Cube License", URL: "https://fedoraproject.org/wiki/Licensing/Cube"},
	"curl":                             {Identifier: "curl", Name: "curl License", URL: "https://github.com/bagder/curl/blob/master/COPYING"},
	"D-FSL-1.0":                        {Identifier: "D-FSL-1.0", Name: "Deutsche Freie Software Lizenz", URL: "http://www.dipp.nrw.de/d-fsl/lizenzen/"},
	"diffmark":                         {Identifier: "diffmark", Name: "diffmark license", URL: "https://fedoraproject.org/wiki/Licensing/diffmark"},
	"WTFPL":                            {Identifier: "WTFPL", Name: "Do What The F*ck You Want To Public License", URL: "http://sam.zoy.org/wtfpl/COPYING"},
	"DOC":                              {Identifier: "DOC", Name: "DOC License", URL: "http://www.cs.wustl.edu/~schmidt/ACE-copying.html"},
	"Dotseqn":                          {Identifier: "Dotseqn", Name: "Dotseqn License", URL: "https://fedoraproject.org/wiki/Licensing/Dotseqn"},
	"DSDP":                             {Identifier: "DSDP", Name: "DSDP License", URL: "https://fedoraproject.org/wiki/Licensing/DSDP"},
	"dvipdfm":                          {Identifier: "dvipdfm", Name: "dvipdfm License", URL: "https://fedoraproject.org/wiki/Licensing/dvipdfm"},
	"EPL-1.0":                          {Identifier: "EPL-1.0", Name: "Eclipse Public License 1.0", URL: "http://www.eclipse.org/legal/epl-v10.html"},
	"ECL-1.0":                          {Identifier: "ECL-1.0", Name: "Educational Community License v1.0", URL: "http://opensource.org/licenses/ECL-1.0"},
	"ECL-2.0":                          {Identifier: "ECL-2.0", Name: "Educational Community License v2.0", URL: "http://opensource.org/licenses/ECL-2.0"},
	"eGenix":                           {Identifier: "eGenix", Name: "eGenix.com Public License 1.1.0", URL: "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf"},
	"EFL-1.0":                          {Identifier: "EFL-1.0", Name: "Eiffel Forum License v1.0", URL: "http://www.eiffel-nice.org/license/forum.txt"},
	"EFL-2.0":                          {Identifier: "EFL-2.0", Name: "Eiffel Forum License v2.0", URL: "http://www.eiffel-nice.org/license/eiffel-forum-license-2.html"},
	"MIT-advertising":                  {Identifier: "MIT-advertising", Name: "Enlightenment License (e16)", URL: "https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising"},
	"MIT-enna":                         {Identifier: "MIT-enna", Name: "enna License", URL: "https://fedoraproject.org/wiki/Licensing/MIT#enna"},
	"Entessa":                          {Identifier: "Entessa", Name: "Entessa Public License v1.0", URL: "http://opensource.org/licenses/Entessa"},
	"ErlPL-1.1":                        {Identifier: "ErlPL-1.1", Name: "Erlang Public License v1.1", URL: "http://www.erlang.org/EPLICENSE"},
	"EUDatagrid":                       {Identifier: "EUDatagrid", Name: "EU DataGrid Software License", URL: "http://eu-datagrid.web.cern.ch/eu-datagrid/license.html"},
	"EUPL-1.0":                         {Identifier: "EUPL-1.0", Name: "European Union Public License 1.0", URL: "http://ec.europa.eu/idabc/en/document/7330.html"},
	"EUPL-1.1":                         {Identifier: "EUPL-1.1", Name: "European Union Public License 1.1", URL: "https://joinup.ec.europa.eu/software/page/eupl/licence-eupl"},
	"Eurosym":                          {Identifier: "Eurosym", Name: "Eurosym License", URL: "https://fedoraproject.org/wiki/Licensing/Eurosym"},
	"Fair":                             {Identifier: "Fair", Name: "Fair License", URL: "http://www.opensource.org/licenses/Fair"},
	"MIT-feh":                          {Identifier: "MIT-feh", Name: "feh License", URL: "https://fedoraproject.org/wiki/Licensing/MIT#feh"},
	"Frameworx-1.0":                    {Identifier: "Frameworx-1.0", Name: "Frameworx Open License 1.0", URL: "http://www.opensource.org/licenses/Frameworx-1.0"},
	"FreeImage":                        {Identifier: "FreeImage", Name: "FreeImage Public License v1.0", URL: "http://freeimage.sourceforge.net/freeimage-license.txt"},
	"FTL":                              {Identifier: "FTL", Name: "Freetype Project License", URL: "http://freetype.fis.uniroma2.it/FTL.TXT"},
	"FSFAP":                            {Identifier: "FSFAP", Name: "FSF All Permissive License", URL: "http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html"},
	"FSFUL":                            {Identifier: "FSFUL", Name: "FSF Unlimited License", URL: "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License"},
	"FSFULLR":                          {Identifier: "FSFULLR", Name: "FSF Unlimited License (with License Retention)", URL: "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"},
	"Giftware":                         {Identifier: "Giftware", Name: "Giftware License", URL: "http://alleg.sourceforge.net//license.html"},
	"GL2PS":                            {Identifier: "GL2PS", Name: "GL2PS License", URL: "http://www.geuz.org/gl2ps/COPYING.GL2PS"},
	"Glulxe":                           {Identifier: "Glulxe", Name: "Glulxe License", URL: "https://fedoraproject.org/wiki/Licensing/Glulxe"},
	"AGPL-3.0":                         {Identifier: "AGPL-3.0", Name: "GNU Affero General Public License v3.0", URL: "http://www.gnu.org/licenses/agpl.txt"},
	"GFDL-1.1":                         {Identifier: "GFDL-1.1", Name: "GNU Free Documentation License v1.1", URL: "http://www.gnu.org/licenses/old-licenses/fdl-1.1.txt"},
	"GFDL-1.2":                         {Identifier: "GFDL-1.2", Name: "GNU Free Documentation License v1.2", URL: "http://www.gnu.org/licenses/old-licenses/fdl-1.2.txt"},
	"GFDL-1.3":                         {Identifier: "GFDL-1.3", Name: "GNU Free Documentation License v1.3", URL: "http://www.gnu.org/licenses/fdl-1.3.txt"},
	"GPL-1.0":                          {Identifier: "GPL-1.0", Name: "GNU General Public License v1.0 only", URL: "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html"},
	"GPL-2.0":                          {Identifier: "GPL-2.0", Name: "GNU General Public License v2.0 only", URL: "http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html"},
	"GPL-3.0":                          {Identifier: "GPL-3.0", Name: "GNU General Public License v3.0 only", URL: "http://www.gnu.org/licenses/gpl-3.0-standalone.html"},
	"LGPL-2.1":                         {Identifier: "LGPL-2.1", Name: "GNU Lesser General Public License v2.1 only", URL: "http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html"},
	"LGPL-3.0":                         {Identifier: "LGPL-3.0", Name: "GNU Lesser General Public License v3.0 only", URL: "http://www.gnu.org/licenses/lgpl-3.0-standalone.html"},
	"LGPL-2.0":                         {Identifier: "LGPL-2.0", Name: "GNU Library General Public License v2 only", URL: "http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html"},
	"gnuplot":                          {Identifier: "gnuplot", Name: "gnuplot License", URL: "https://fedoraproject.org/wiki/Licensing/Gnuplot"},
	"gSOAP-1.3b":                       {Identifier: "gSOAP-1.3b", Name: "gSOAP Public License v1.3b", URL: "http://www.cs.fsu.edu/~engelen/license.html"},
	"HaskellReport":                    {Identifier: "HaskellReport", Name: "Haskell Language Report License", URL: "https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License"},
	"HPND":                             {Identifier: "HPND", Name: "Historic Permission Notice and Disclaimer", URL: "http://www.opensource.org/licenses/HPND"},
	"IBM-pibs":                         {Identifier: "IBM-pibs", Name: "IBM PowerPC Initialization and Boot Software", URL: "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"},
	"IPL-1.0":                          {Identifier: "IPL-1.0", Name: "IBM Public License v1.0", URL: "http://www.opensource.org/licenses/IPL-1.0"},
	"ICU":                              {Identifier: "ICU", Name: "ICU License", URL: "http://source.icu-project.org/repos/icu/icu/trunk/license.html"},
	"ImageMagick":                      {Identifier: "ImageMagick", Name: "ImageMagick License", URL: "http://www.imagemagick.org/script/license.php"},
	"iMatix":                           {Identifier: "iMatix", Name: "iMatix Standard Function Library Agreement", URL: "http://legacy.imatix.com/html/sfl/sfl4.htm#license"},
	"Imlib2":                           {Identifier: "Imlib2", Name: "Imlib2 License", URL: "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING"},
	"IJG":                              {Identifier: "IJG", Name: "Independent JPEG Group License", URL: "http://dev.w3.org/cvsweb/Amaya/libjpeg/Attic/README?rev=1.2"},
	"Info-ZIP":                         {Identifier: "Info-ZIP", Name: "Info-ZIP License", URL: "http://www.info-zip.org/license.html"},
	"Intel-ACPI":                       {Identifier: "Intel-ACPI", Name: "Intel ACPI Software License Agreement", URL: "https://fedoraproject.org/wiki/Licensing/Intel_ACPI_Software_License_Agreement"},
	"Intel":                            {Identifier: "Intel", Name: "Intel Open Source License", URL: "http://opensource.org/licenses/Intel"},
	"Interbase-1.0":                    {Identifier: "Interbase-1.0", Name: "Interbase Public License v1.0", URL: "https://web.archive.org/web/20060319014854/http://info.borland.com/devsupport/interbase/opensource/IPL.html"},
	"IPA":                              {Identifier: "IPA", Name: "IPA Font License", URL: "http://www.opensource.org/licenses/IPA"},
	"ISC":                              {Identifier: "ISC", Name: "ISC License", URL: "http://www.isc.org/software/license"},
	"JasPer-2.0":                       {Identifier: "JasPer-2.0", Name: "JasPer License", URL: "http://www.ece.uvic.ca/~mdadams/jasper/LICENSE"},
	"JSON":                             {Identifier: "JSON", Name: "JSON License", URL: "http://www.json.org/license.html"},
	"LPPL-1.0":                         {Identifier: "LPPL-1.0", Name: "LaTeX Project Public License v1.0", URL: "http://www.latex-project.org/lppl/lppl-1-0.txt"},
	"LPPL-1.1":                         {Identifier: "LPPL-1.1", Name: "LaTeX Project Public License v1.1", URL: "http://www.latex-project.org/lppl/lppl-1-1.txt"},
	"LPPL-1.2":                         {Identifier: "LPPL-1.2", Name: "LaTeX Project Public License v1.2", URL: "http://www.latex-project.org/lppl/lppl-1-2.txt"},
	"LPPL-1.3a":                        {Identifier: "LPPL-1.3a", Name: "LaTeX Project Public License v1.3a", URL: "http://www.latex-project.org/lppl/lppl-1-3a.txt"},
	"LPPL-1.3c":                        {Identifier: "LPPL-1.3c", Name: "LaTeX Project Public License v1.3c", URL: "http://www.latex-project.org/lppl/lppl-1-3c.txt"},
	"Latex2e":                          {Identifier: "Latex2e", Name: "Latex2e License", URL: "https://fedoraproject.org/wiki/Licensing/Latex2e"},
	"BSD-3-Clause-LBNL":                {Identifier: "BSD-3-Clause-LBNL", Name: "Lawrence Berkeley National Labs BSD variant license", URL: "https://fedoraproject.org/wiki/Licensing/LBNLBSD"},
	"Leptonica":                        {Identifier: "Leptonica", Name: "Leptonica License", URL: "https://fedoraproject.org/wiki/Licensing/Leptonica"},
	"LGPLLR":                           {Identifier: "LGPLLR", Name: "Lesser General Public License For Linguistic Resources", URL: "http://www-igm.univ-mlv.fr/~unitex/lgpllr.html"},
	"Libpng":                           {Identifier: "Libpng", Name: "libpng License", URL: "http://www.libpng.org/pub/png/src/libpng-LICENSE.txt"},
	"libtiff":                          {Identifier: "libtiff", Name: "libtiff License", URL: "https://fedoraproject.org/wiki/Licensing/libtiff"},
	"LAL-1.2":                          {Identifier: "LAL-1.2", Name: "Licence Art Libre 1.2", URL: "http://artlibre.org/licence/lal/licence-art-libre-12/"},
	"LAL-1.3":                          {Identifier: "LAL-1.3", Name: "Licence Art Libre 1.3", URL: "http://artlibre.org/"},
	"LiLiQ-P-1.1":                      {Identifier: "LiLiQ-P-1.1", Name: "Licence Libre du Québec – Permissive version 1.1", URL: "http://opensource.org/licenses/LiLiQ-P-1.1"},
	"LiLiQ-Rplus-1.1":                  {Identifier: "LiLiQ-Rplus-1.1", Name: "Licence Libre du Québec – Réciprocité forte version 1.1", URL: "http://opensource.org/licenses/LiLiQ-Rplus-1.1"},
	"LiLiQ-R-1.1":                      {Identifier: "LiLiQ-R-1.1", Name: "Licence Libre du Québec – Réciprocité version 1.1", URL: "http://opensource.org/licenses/LiLiQ-R-1.1"},
	"LPL-1.02":                         {Identifier: "LPL-1.02", Name: "Lucent Public License v1.02", URL: "http://plan9.bell-labs.com/plan9/license.html"},
	"LPL-1.0":                          {Identifier: "LPL-1.0", Name: "Lucent Public License Version 1.0", URL: "http://opensource.org/licenses/LPL-1.0"},
	"MakeIndex":                        {Identifier: "MakeIndex", Name: "MakeIndex License", URL: "https://fedoraproject.org/wiki/Licensing/MakeIndex"},
	"MTLL":                             {Identifier: "MTLL", Name: "Matrix Template Library License", URL: "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"},
	"MS-PL":                            {Identifier: "MS-PL", Name: "Microsoft Public License", URL: "http://www.microsoft.com/opensource/licenses.mspx"},
	"MS-RL":                            {Identifier: "MS-RL", Name: "Microsoft Reciprocal License", URL: "http://www.microsoft.com/opensource/licenses.mspx"},
	"MirOS":                            {Identifier: "MirOS", Name: "MirOS Licence", URL: "http://www.opensource.org/licenses/MirOS"},
	"MITNFA":                           {Identifier: "MITNFA", Name: "MIT +no-false-attribs license", URL: "https://fedoraproject.org/wiki/Licensing/MITNFA"},
	"MIT":                              {Identifier: "MIT", Name: "MIT License", URL: "http://www.opensource.org/licenses/MIT"},
	"Motosoto":                         {Identifier: "Motosoto", Name: "Motosoto License", URL: "http://www.opensource.org/licenses/Motosoto"},
	"MPL-1.0":                          {Identifier: "MPL-1.0", Name: "Mozilla Public License 1.0", URL: "http://www.mozilla.org/MPL/MPL-1.0.html"},
	"MPL-1.1":                          {Identifier: "MPL-1.1", Name: "Mozilla Public License 1.1", URL: "http://www.mozilla.org/MPL/MPL-1.1.html"},
	"MPL-2.0":                          {Identifier: "MPL-2.0", Name: "Mozilla Public License 2.0", URL: "http://www.mozilla.org/MPL/2.0/"},
	"MPL-2.0-no-copyleft-exception":    {Identifier: "MPL-2.0-no-copyleft-exception", Name: "Mozilla Public License 2.0 (no copyleft exception)", URL: "http://www.mozilla.org/MPL/2.0/"},
	"mpich2":                           {Identifier: "mpich2", Name: "mpich2 License", URL: "https://fedoraproject.org/wiki/Licensing/MIT"},
	"Multics":                          {Identifier: "Multics", Name: "Multics License", URL: "http://www.opensource.org/licenses/Multics"},
	"Mup":                              {Identifier: "Mup", Name: "Mup License", URL: "https://fedoraproject.org/wiki/Licensing/Mup"},
	"NASA-1.3":                         {Identifier: "NASA-1.3", Name: "NASA Open Source Agreement 1.3", URL: "http://ti.arc.nasa.gov/opensource/nosa/"},
	"Naumen":                           {Identifier: "Naumen", Name: "Naumen Public License", URL: "http://www.opensource.org/licenses/Naumen"},
	"NBPL-1.0":                         {Identifier: "NBPL-1.0", Name: "Net Boolean Public License v1", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=37b4b3f6cc4bf34e1d3dec61e69914b9819d8894"},
	"Net-SNMP":                         {Identifier: "Net-SNMP", Name: "Net-SNMP License", URL: "http://net-snmp.sourceforge.net/about/license.html"},
	"NetCDF":                           {Identifier: "NetCDF", Name: "NetCDF license", URL: "http://www.unidata.ucar.edu/software/netcdf/copyright.html"},
	"NGPL":                             {Identifier: "NGPL", Name: "Nethack General Public License", URL: "http://www.opensource.org/licenses/NGPL"},
	"NOSL":                             {Identifier: "NOSL", Name: "Netizen Open Source License", URL: "http://bits.netizen.com.au/licenses/NOSL/nosl.txt"},
	"NPL-1.0":                          {Identifier: "NPL-1.0", Name: "Netscape Public License v1.0", URL: "http://www.mozilla.org/MPL/NPL/1.0/"},
	"NPL-1.1":                          {Identifier: "NPL-1.1", Name: "Netscape Public License v1.1", URL: "http://www.mozilla.org/MPL/NPL/1.1/"},
	"Newsletr":                         {Identifier: "Newsletr", Name: "Newsletr License", URL: "https://fedoraproject.org/wiki/Licensing/Newsletr"},
	"NLPL":                             {Identifier: "NLPL", Name: "No Limit Public License", URL: "https://fedoraproject.org/wiki/Licensing/NLPL"},
	"Nokia":                            {Identifier: "Nokia", Name: "Nokia Open Source License", URL: "http://www.opensource.org/licenses/nokia"},
	"NPOSL-3.0":                        {Identifier: "NPOSL-3.0", Name: "Non-Profit Open Software License 3.0", URL: "http://www.opensource.org/licenses/NOSL3.0"},
	"NLOD-1.0":                         {Identifier: "NLOD-1.0", Name: "Norwegian Licence for Open Government Data", URL: "http://data.norge.no/nlod/en/1.0"},
	"Noweb":                            {Identifier: "Noweb", Name: "Noweb License", URL: "https://fedoraproject.org/wiki/Licensing/Noweb"},
	"NRL":                              {Identifier: "NRL", Name: "NRL License", URL: "http://web.mit.edu/network/isakmp/nrllicense.html"},
	"NTP":                              {Identifier: "NTP", Name: "NTP License", URL: "http://www.opensource.org/licenses/NTP"},
	"Nunit":                            {Identifier: "Nunit", Name: "Nunit License", URL: "https://fedoraproject.org/wiki/Licensing/Nunit"},
	"OCLC-2.0":                         {Identifier: "OCLC-2.0", Name: "OCLC Research Public License 2.0", URL: "http://www.oclc.org/research/activities/software/license/v2final.htm"},
	"ODbL-1.0":                         {Identifier: "ODbL-1.0", Name: "ODC Open Database License v1.0", URL: "http://www.opendatacommons.org/licenses/odbl/1.0/"},
	"PDDL-1.0":                         {Identifier: "PDDL-1.0", Name: "ODC Public Domain Dedication & License 1.0", URL: "http://opendatacommons.org/licenses/pddl/1.0/"},
	"OCCT-PL":                          {Identifier: "OCCT-PL", Name: "Open CASCADE Technology Public License", URL: "http://www.opencascade.com/content/occt-public-license"},
	"OGTSL":                            {Identifier: "OGTSL", Name: "Open Group Test Suite License", URL: "http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt"},
	"OLDAP-2.2.2":                      {Identifier: "OLDAP-2.2.2", Name: "Open LDAP Public License  2.2.2", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=df2cc1e21eb7c160695f5b7cffd6296c151ba188"},
	"OLDAP-1.1":                        {Identifier: "OLDAP-1.1", Name: "Open LDAP Public License v1.1", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=806557a5ad59804ef3a44d5abfbe91d706b0791f"},
	"OLDAP-1.2":                        {Identifier: "OLDAP-1.2", Name: "Open LDAP Public License v1.2", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=42b0383c50c299977b5893ee695cf4e486fb0dc7"},
	"OLDAP-1.3":                        {Identifier: "OLDAP-1.3", Name: "Open LDAP Public License v1.3", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=e5f8117f0ce088d0bd7a8e18ddf37eaa40eb09b1"},
	"OLDAP-1.4":                        {Identifier: "OLDAP-1.4", Name: "Open LDAP Public License v1.4", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=c9f95c2f3f2ffb5e0ae55fe7388af75547660941"},
	"OLDAP-2.0":                        {Identifier: "OLDAP-2.0", Name: "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cbf50f4e1185a21abd4c0a54d3f4341fe28f36ea"},
	"OLDAP-2.0.1":                      {Identifier: "OLDAP-2.0.1", Name: "Open LDAP Public License v2.0.1", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"},
	"OLDAP-2.1":                        {Identifier: "OLDAP-2.1", Name: "Open LDAP Public License v2.1", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"},
	"OLDAP-2.2":                        {Identifier: "OLDAP-2.2", Name: "Open LDAP Public License v2.2", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=470b0c18ec67621c85881b2733057fecf4a1acc3"},
	"OLDAP-2.2.1":                      {Identifier: "OLDAP-2.2.1", Name: "Open LDAP Public License v2.2.1", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=4bc786f34b50aa301be6f5600f58a980070f481e"},
	"OLDAP-2.3":                        {Identifier: "OLDAP-2.3", Name: "Open LDAP Public License v2.3", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3"},
	"OLDAP-2.4":                        {Identifier: "OLDAP-2.4", Name: "Open LDAP Public License v2.4", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cd1284c4a91a8a380d904eee68d1583f989ed386"},
	"OLDAP-2.5":                        {Identifier: "OLDAP-2.5", Name: "Open LDAP Public License v2.5", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=6852b9d90022e8593c98205413380536b1b5a7cf"},
	"OLDAP-2.6":                        {Identifier: "OLDAP-2.6", Name: "Open LDAP Public License v2.6", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=1cae062821881f41b73012ba816434897abf4205"},
	"OLDAP-2.7":                        {Identifier: "OLDAP-2.7", Name: "Open LDAP Public License v2.7", URL: "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=47c2415c1df81556eeb39be6cad458ef87c534a2"},
	"OLDAP-2.8":                        {Identifier: "OLDAP-2.8", Name: "Open LDAP Public License v2.8", URL: "http://www.openldap.org/software/release/license.html"},
	"OML":                              {Identifier: "OML", Name: "Open Market License", URL: "https://fedoraproject.org/wiki/Licensing/Open_Market_License"},
	"OPL-1.0":                          {Identifier: "OPL-1.0", Name: "Open Public License v1.0", URL: "http://old.koalateam.com/jackaroo/OPL_1_0.TXT"},
	"OSL-1.0":                          {Identifier: "OSL-1.0", Name: "Open Software License 1.0", URL: "http://opensource.org/licenses/OSL-1.0"},
	"OSL-1.1":                          {Identifier: "OSL-1.1", Name: "Open Software License 1.1", URL: "https://fedoraproject.org/wiki/Licensing/OSL1.1"},
	"OSL-2.0":                          {Identifier: "OSL-2.0", Name: "Open Software License 2.0", URL: "http://web.archive.org/web/20041020171434/http://www.rosenlaw.com/osl2.0.html"},
	"OSL-2.1":                          {Identifier: "OSL-2.1", Name: "Open Software License 2.1", URL: "http://opensource.org/licenses/OSL-2.1"},
	"OSL-3.0":                          {Identifier: "OSL-3.0", Name: "Open Software License 3.0", URL: "http://www.rosenlaw.com/OSL3.0.htm"},
	"OpenSSL":                          {Identifier: "OpenSSL", Name: "OpenSSL License", URL: "http://www.openssl.org/source/license.html"},
	"OSET-PL-2.1":                      {Identifier: "OSET-PL-2.1", Name: "OSET Public License version 2.1", URL: "http://opensource.org/licenses/OPL-2.1"},
	"PHP-3.0":                          {Identifier: "PHP-3.0", Name: "PHP License v3.0", URL: "http://www.opensource.org/licenses/PHP-3.0"},
	"PHP-3.01":                         {Identifier: "PHP-3.01", Name: "PHP License v3.01", URL: "http://www.php.net/license/3_01.txt"},
	"Plexus":                           {Identifier: "Plexus", Name: "Plexus Classworlds License", URL: "https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License"},
	"PostgreSQL":                       {Identifier: "PostgreSQL", Name: "PostgreSQL License", URL: "http://www.postgresql.org/about/licence"},
	"psfrag":                           {Identifier: "psfrag", Name: "psfrag License", URL: "https://fedoraproject.org/wiki/Licensing/psfrag"},
	"psutils":                          {Identifier: "psutils", Name: "psutils License", URL: "https://fedoraproject.org/wiki/Licensing/psutils"},
	"Python-2.0":                       {Identifier: "Python-2.0", Name: "Python License 2.0", URL: "http://www.opensource.org/licenses/Python-2.0"},
	"QPL-1.0":                          {Identifier: "QPL-1.0", Name: "Q Public License 1.0", URL: "http://doc.qt.nokia.com/3.3/license.html"},
	"Qhull":                            {Identifier: "Qhull", Name: "Qhull License", URL: "https://fedoraproject.org/wiki/Licensing/Qhull"},
	"Rdisc":                            {Identifier: "Rdisc", Name: "Rdisc License", URL: "https://fedoraproject.org/wiki/Licensing/Rdisc_License"},
	"RPSL-1.0":                         {Identifier: "RPSL-1.0", Name: "RealNetworks Public Source License v1.0", URL: "https://helixcommunity.org/content/rpsl"},
	"RPL-1.1":                          {Identifier: "RPL-1.1", Name: "Reciprocal Public License 1.1", URL: "http://opensource.org/licenses/RPL-1.1"},
	"RPL-1.5":                          {Identifier: "RPL-1.5", Name: "Reciprocal Public License 1.5", URL: "http://www.opensource.org/licenses/RPL-1.5"},
	"RHeCos-1.1":                       {Identifier: "RHeCos-1.1", Name: "Red Hat eCos Public License v1.1", URL: "http://ecos.sourceware.org/old-license.html"},
	"RSCPL":                            {Identifier: "RSCPL", Name: "Ricoh Source Code Public License", URL: "http://www.opensource.org/licenses/RSCPL"},
	"RSA-MD":                           {Identifier: "RSA-MD", Name: "RSA Message-Digest License ", URL: "http://www.faqs.org/rfcs/rfc1321.html"},
	"Ruby":                             {Identifier: "Ruby", Name: "Ruby License", URL: "http://www.ruby-lang.org/en/LICENSE.txt"},
	"SAX-PD":                           {Identifier: "SAX-PD", Name: "Sax Public Domain Notice", URL: "http://www.saxproject.org/copying.html"},
	"Saxpath":                          {Identifier: "Saxpath", Name: "Saxpath License", URL: "https://fedoraproject.org/wiki/Licensing/Saxpath_License"},
	"SCEA":                             {Identifier: "SCEA", Name: "SCEA Shared Source License", URL: "http://research.scea.com/scea_shared_source_license.html"},
	"SWL":                              {Identifier: "SWL", Name: "Scheme Widget Library (SWL) Software License Agreement", URL: "https://fedoraproject.org/wiki/Licensing/SWL"},
	"SMPPL":                            {Identifier: "SMPPL", Name: "Secure Messaging Protocol Public License", URL: "https://github.com/dcblake/SMP/blob/master/Documentation/License.txt"},
	"Sendmail":                         {Identifier: "Sendmail", Name: "Sendmail License", URL: "http://www.sendmail.com/pdfs/open_source/sendmail_license.pdf"},
	"SGI-B-1.0":                        {Identifier: "SGI-B-1.0", Name: "SGI Free Software License B v1.0", URL: "http://oss.sgi.com/projects/FreeB/SGIFreeSWLicB.1.0.html"},
	"SGI-B-1.1":                        {Identifier: "SGI-B-1.1", Name: "SGI Free Software License B v1.1", URL: "http://oss.sgi.com/projects/FreeB/"},
	"SGI-B-2.0":                        {Identifier: "SGI-B-2.0", Name: "SGI Free Software License B v2.0", URL: "http://oss.sgi.com/projects/FreeB/SGIFreeSWLicB.2.0.pdf"},
	"OFL-1.0":                          {Identifier: "OFL-1.0", Name: "SIL Open Font License 1.0", URL: "http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web"},
	"OFL-1.1":                          {Identifier: "OFL-1.1", Name: "SIL Open Font License 1.1", URL: "http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web"},
	"SimPL-2.0":                        {Identifier: "SimPL-2.0", Name: "Simple Public License 2.0", URL: "http://www.opensource.org/licenses/SimPL-2.0"},
	"Sleepycat":                        {Identifier: "Sleepycat", Name: "Sleepycat License", URL: "http://www.opensource.org/licenses/Sleepycat"},
	"SNIA":                             {Identifier: "SNIA", Name: "SNIA Public License 1.1", URL: "https://fedoraproject.org/wiki/Licensing/SNIA_Public_License"},
	"Spencer-86":                       {Identifier: "Spencer-86", Name: "Spencer License 86", URL: "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"},
	"Spencer-94":                       {Identifier: "Spencer-94", Name: "Spencer License 94", URL: "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"},
	"Spencer-99":                       {Identifier: "Spencer-99", Name: "Spencer License 99", URL: "http://www.opensource.apple.com/source/tcl/tcl-5/tcl/generic/regfronts.c"},
	"SMLNJ":                            {Identifier: "SMLNJ", Name: "Standard ML of New Jersey License", URL: "http://www.smlnj.org//license.html"},
	"SugarCRM-1.1.3":                   {Identifier: "SugarCRM-1.1.3", Name: "SugarCRM Public License v1.1.3", URL: "http://www.sugarcrm.com/crm/SPL"},
	"SISSL":                            {Identifier: "SISSL", Name: "Sun Industry Standards Source License v1.1", URL: "http://www.openoffice.org/licenses/sissl_license.html"},
	"SISSL-1.2":                        {Identifier: "SISSL-1.2", Name: "Sun Industry Standards Source License v1.2", URL: "http://gridscheduler.sourceforge.net/Gridengine_SISSL_license.html"},
	"SPL-1.0":                          {Identifier: "SPL-1.0", Name: "Sun Public License v1.0", URL: "http://www.opensource.org/licenses/SPL-1.0"},
	"Watcom-1.0":                       {Identifier: "Watcom-1.0", Name: "Sybase Open Watcom Public License 1.0", URL: "http://www.opensource.org/licenses/Watcom-1.0"},
	"TCL":                              {Identifier: "TCL", Name: "TCL/TK License", URL: "http://www.tcl.tk/software/tcltk/license.html"},
	"TCP-wrappers":                     {Identifier: "TCP-wrappers", Name: "TCP Wrappers License", URL: "http://rc.quest.com/topics/openssh/license.php#tcpwrappers"},
	"Unlicense":                        {Identifier: "Unlicense", Name: "The Unlicense", URL: "http://unlicense.org/"},
	"TMate":                            {Identifier: "TMate", Name: "TMate Open Source License", URL: "http://svnkit.com/license.html"},
	"TORQUE-1.1":                       {Identifier: "TORQUE-1.1", Name: "TORQUE v2.5+ Software License v1.1", URL: "https://fedoraproject.org/wiki/Licensing/TORQUEv1.1"},
	"TOSL":                             {Identifier: "TOSL", Name: "Trusster Open Source License", URL: "https://fedoraproject.org/wiki/Licensing/TOSL"},
	"Unicode-DFS-2015":                 {Identifier: "Unicode-DFS-2015", Name: "Unicode License Agreement - Data Files and Software (2015)", URL: "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"},
	"Unicode-DFS-2016":                 {Identifier: "Unicode-DFS-2016", Name: "Unicode License Agreement - Data Files and Software (2016)", URL: "http://www.unicode.org/copyright.html"},
	"Unicode-TOU":                      {Identifier: "Unicode-TOU", Name: "Unicode Terms of Use", URL: "http://www.unicode.org/copyright.html"},
	"UPL-1.0":                          {Identifier: "UPL-1.0", Name: "Universal Permissive License v1.0", URL: "http://opensource.org/licenses/UPL"},
	"NCSA":                             {Identifier: "NCSA", Name: "University of Illinois/NCSA Open Source License", URL: "http://otm.illinois.edu/uiuc_openSource"},
	"Vim":                              {Identifier: "Vim", Name: "Vim License", URL: "http://vimdoc.sourceforge.net/htmldoc/uganda.html"},
	"VOSTROM":                          {Identifier: "VOSTROM", Name: "VOSTROM Public License for Open Source", URL: "https://fedoraproject.org/wiki/Licensing/VOSTROM"},
	"VSL-1.0":                          {Identifier: "VSL-1.0", Name: "Vovida Software License v1.0", URL: "http://www.opensource.org/licenses/VSL-1.0"},
	"W3C-20150513":                     {Identifier: "W3C-20150513", Name: "W3C Software Notice and Document License (2015-05-13)", URL: "https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document"},
	"W3C-19980720":                     {Identifier: "W3C-19980720", Name: "W3C Software Notice and License (1998-07-20)", URL: "http://www.w3.org/Consortium/Legal/copyright-software-19980720.html"},
	"W3C":                              {Identifier: "W3C", Name: "W3C Software Notice and License (2002-12-31)", URL: "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"},
	"Wsuipa":                           {Identifier: "Wsuipa", Name: "Wsuipa License", URL: "https://fedoraproject.org/wiki/Licensing/Wsuipa"},
	"Xnet":                             {Identifier: "Xnet", Name: "X.Net License", URL: "http://opensource.org/licenses/Xnet"},
	"X11":                              {Identifier: "X11", Name: "X11 License", URL: "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"},
	"Xerox":                            {Identifier: "Xerox", Name: "Xerox License", URL: "https://fedoraproject.org/wiki/Licensing/Xerox"},
	"XFree86-1.1":                      {Identifier: "XFree86-1.1", Name: "XFree86 License 1.1", URL: "http://www.xfree86.org/current/LICENSE4.html"},
	"xinetd":                           {Identifier: "xinetd", Name: "xinetd License", URL: "https://fedoraproject.org/wiki/Licensing/Xinetd_License"},
	"xpp":                              {Identifier: "xpp", Name: "XPP License", URL: "https://fedoraproject.org/wiki/Licensing/xpp"},
	"XSkat":                            {Identifier: "XSkat", Name: "XSkat License", URL: "https://fedoraproject.org/wiki/Licensing/XSkat_License"},
	"YPL-1.0":                          {Identifier: "YPL-1.0", Name: "Yahoo! Public License v1.0", URL: "http://www.zimbra.com/license/yahoo_public_license_1.0.html"},
	"YPL-1.1":                          {Identifier: "YPL-1.1", Name: "Yahoo! Public License v1.1", URL: "http://www.zimbra.com/license/yahoo_public_license_1.1.html"},
	"Zed":                              {Identifier: "Zed", Name: "Zed License", URL: "https://fedoraproject.org/wiki/Licensing/Zed"},
	"Zend-2.0":                         {Identifier: "Zend-2.0", Name: "Zend License v2.0", URL: "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"},
	"Zimbra-1.3":                       {Identifier: "Zimbra-1.3", Name: "Zimbra Public License v1.3", URL: ""},
	"Zimbra-1.4":                       {Identifier: "Zimbra-1.4", Name: "Zimbra Public License v1.4", URL: "http://www.zimbra.com/legal/zimbra-public-license-1-4"},
	"Zlib":                             {Identifier: "Zlib", Name: "zlib License", URL: "http://www.zlib.net/zlib_license.html"},
	"zlib-acknowledgement":             {Identifier: "zlib-acknowledgement", Name: "zlib/libpng License with Acknowledgement", URL: "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"},
	"ZPL-1.1":                          {Identifier: "ZPL-1.1", Name: "Zope Public License 1.1", URL: "http://old.zope.org/Resources/License/ZPL-1.1"},
	"ZPL-2.0":                          {Identifier: "ZPL-2.0", Name: "Zope Public License 2.0", URL: "http://old.zope.org/Resources/License/ZPL-2.0"},
	"ZPL-2.1":                          {Identifier: "ZPL-2.1", Name: "Zope Public License 2.1", URL: "http://old.zope.org/Resources/ZPL/"},
	"eCos-2.0":                         {Identifier: "eCos-2.0", Name: "eCos license version 2.0", URL: "http://www.gnu.org/licenses/ecos-license.html"},
	"GPL-1.0+":                         {Identifier: "GPL-1.0+", Name: "GNU General Public License v1.0 or later", URL: "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html"},
	"GPL-2.0+":                         {Identifier: "GPL-2.0+", Name: "GNU General Public License v2.0 or later", URL: "http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html"},
	"GPL-2.0-with-autoconf-exception":  {Identifier: "GPL-2.0-with-autoconf-exception", Name: "GNU General Public License v2.0 w/Autoconf exception", URL: "http://ac-archive.sourceforge.net/doc/copyright.html"},
	"GPL-2.0-with-bison-exception":     {Identifier: "GPL-2.0-with-bison-exception", Name: "GNU General Public License v2.0 w/Bison exception", URL: "none"},
	"GPL-2.0-with-classpath-exception": {Identifier: "GPL-2.0-with-classpath-exception", Name: "GNU General Public License v2.0 w/Classpath exception", URL: "http://www.gnu.org/software/classpath/license.html"},
	"GPL-2.0-with-font-exception":      {Identifier: "GPL-2.0-with-font-exception", Name: "GNU General Public License v2.0 w/Font exception", URL: "http://www.gnu.org/licenses/gpl-faq.html#FontException"},
	"GPL-2.0-with-GCC-exception":       {Identifier: "GPL-2.0-with-GCC-exception", Name: "GNU General Public License v2.0 w/GCC Runtime Library exception", URL: "none"},
	"GPL-3.0+":                         {Identifier: "GPL-3.0+", Name: "GNU General Public License v3.0 or later", URL: "http://www.gnu.org/licenses/gpl-3.0-standalone.html"},
	"GPL-3.0-with-autoconf-exception":  {Identifier: "GPL-3.0-with-autoconf-exception", Name: "GNU General Public License v3.0 w/Autoconf exception", URL: "http://www.gnu.org/licenses/autoconf-exception-3.0.html"},
	"GPL-3.0-with-GCC-exception":       {Identifier: "GPL-3.0-with-GCC-exception", Name: "GNU General Public License v3.0 w/GCC Runtime Library exception", URL: "http://www.gnu.org/licenses/gcc-exception-3.1.html"},
	"LGPL-2.1+":                        {Identifier: "LGPL-2.1+", Name: "GNU Lesser General Public License v2.1 or later", URL: "http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html"},
	"LGPL-3.0+":                        {Identifier: "LGPL-3.0+", Name: "GNU Lesser General Public License v3.0 or later", URL: "http://www.gnu.org/licenses/lgpl-3.0-standalone.html"},
	"LGPL-2.0+":                        {Identifier: "LGPL-2.0+", Name: "GNU Library General Public License v2 or later", URL: "http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html"},
	"StandardML-NJ":                    {Identifier: "StandardML-NJ", Name: "Standard ML of New Jersey License", URL: "https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Standard_ML_of_New_Jersey_Variant"},
	"WXwindows":                        {Identifier: "WXwindows", Name: "wxWindows Library License", URL: "http://www.opensource.org/licenses/WXwindows"},
}

func GetLicenseFromIdentifier(identifier string) License {
	l, ok := lookup[identifier]
	if !ok {
		return License{
			Identifier: identifier,
			Name:       "Unknown",
		}
	}
	return l
}
