name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test